[option]
exclude_paths = []
textwidth = 80
copyright_linenum = 1
copyright_year = "1234"
copyright_holder = "HOLDER"
indent = 2
prefix_inout = "b_"
prefix_input = "i_"
prefix_output = "o_"
prefix_label = "l_"
prefix_instance = "u_"
prefix_module = "mod_"
prefix_package = "pkg_"
prefix_interface = "ifc_"
re_required_assert = "^[a-z]+[a-z0-9_]*$"
re_required_assert_property = "^[a-z]+[a-z0-9_]*$"
re_required_checker = "^[a-z]+[a-z0-9_]*$"
re_required_class = "^[a-z]+[a-z0-9_]*$"
re_required_function = "^[a-z]+[a-z0-9_]*$"
re_required_generateblock = "^[a-z]+[a-z0-9_]*$"
re_required_genvar = "^[a-z]+[a-z0-9_]*$"
re_required_instance = "^[a-z]+[a-z0-9_]*$"
re_required_interface = "^[a-z]+[a-z0-9_]*$"
re_required_localparam = "^[A-Z]+[A-Z0-9_]*$"
re_required_modport = "^[a-z]+[a-z0-9_]*$"
re_required_module_ansi = "^[a-z]+[a-zA-Z0-9_]*$"
re_required_module_nonansi = "^[A-Z]+[A-Z0-9_]*$"
re_required_package = "^[a-z]+[a-z0-9_]*$"
re_required_parameter = "^[A-Z]+[A-Z0-9_]*$"
re_required_port_inout = "^[a-z]+[a-z0-9_]*$"
re_required_port_input = "^[a-z]+[a-z0-9_]*$"
re_required_port_output = "^[a-z]+[a-z0-9_]*$"
re_required_port_ref = "^[a-z]+[a-z0-9_]*$"
re_required_port_interface = "^[a-z]+[a-z0-9_]*$"
re_required_program = "^[a-z]+[a-z0-9_]*$"
re_required_property = "^[a-z]+[a-z0-9_]*$"
re_required_sequence = "^[a-z]+[a-z0-9_]*$"
re_required_task = "^[a-z]+[a-z0-9_]*$"
re_required_var_class = "^[a-z]+[a-z0-9_]*$"
re_required_var_classmethod = "^[a-z]+[a-z0-9_]*$"
re_forbidden_assert = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_assert_property = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_checker = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_class = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_function = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_generateblock = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_genvar = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_instance = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_interface = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_localparam = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_modport = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_module_ansi = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_module_nonansi = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_package = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_parameter = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_inout = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_input = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_output = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_ref = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_port_interface = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_program = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_property = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_sequence = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_task = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_var_class = "^[^X](UNCONFIGURED|.*)$"
re_forbidden_var_classmethod = "^[^X](UNCONFIGURED|.*)$"

[option.unpacked_array]
localparam_declaration = false
param_declaration = false
specparam_declaration = false
inout_declaration = true
ansi_port_declaration = true
input_declaration = true
output_declaration = true
interface_port_declaration = true
ref_declaration = true
data_declaration = true
net_declaration = true

[textrules]
header_copyright = false # we have other tools that check for this
style_directives = false # NOTE : ngildenhuys :leaving as false, but could be good to change
style_semicolon = true
style_textwidth = true # NOTE : ngildenhuys : may need to change to be 100 or 120 characters

# TODO : ngildenhuys : add personal specific rules you'd like to implement on style

[syntaxrules]
action_block_with_side_effect = true
blocking_assignment_in_always_at_edge = true
blocking_assignment_in_always_ff = true
blocking_assignment_in_always_latch = true
case_default = true
default_nettype_none = true # NOTE : ngildenhuys : this will cause lots of failures
enum_with_type = true
eventlist_comma_always_ff = false # NOTE : ngildenhuys : we  use commas not ors
eventlist_or = true
explicit_case_default = true # NOTE : ngildenhuys: looks like dup of case_default
explicit_if_else = true
function_same_as_system_function = true
function_with_automatic = true # NOTE : ngildenhuys : didn't know sv has lifetimes
general_always_level_sensitive = true
general_always_no_edge = true
# NOTE  : ngildenhuys : doesn't seem all too helpful to label every arm...possible change later
# can also change the label prefix
generate_case_with_label = false
generate_for_with_label = false
generate_if_with_label = false
# NOTE : end
genvar_declaration_in_loop = true
genvar_declaration_out_loop = false
implicit_case_default = true # NOTE : triple on the case default
inout_with_tri = false # NOTE : ngildenhuys : not currently concerned with net types
input_with_var = false # NOTE : ngildenhuys : not currently concerned with net types
interface_identifier_matches_filename = true
interface_port_with_modport = true
keyword_forbidden_always = true
keyword_forbidden_always_comb = false
keyword_forbidden_always_ff = false
keyword_forbidden_always_latch = true
keyword_forbidden_generate = false
keyword_forbidden_logic = false
keyword_forbidden_priority = true # NOTE : ngildenhuys : sim synth mismatch
keyword_forbidden_unique = true # NOTE : ngildenhuys : sim synth mismatch
keyword_forbidden_unique0 = true # NOTE : ngildenhuys : sim synth mismatch
keyword_forbidden_wire_reg = false
keyword_required_generate = false
localparam_explicit_type = true
localparam_type_twostate = true
loop_statement_in_always_comb = true
loop_statement_in_always_ff = false # NOTE : ngildenhuys : because this is a pattern I use in dv code
loop_statement_in_always_latch = true # shouldn't have always latch anywways
loop_variable_declaration = true
lowercamelcase_interface = false
lowercamelcase_module = false
lowercamelcase_package = false
module_ansi_forbidden = false
module_identifier_matches_filename = false # TODO : ngildenhuys : seems buggy for some reason
module_nonansi_forbidden = true
multiline_for_begin = true
multiline_if_begin = true
non_blocking_assignment_in_always_comb = true
non_blocking_assignment_in_always_no_edge = true
operator_case_equality = true
operator_incdec = false
operator_self_assignment = false
output_with_var = false # NOTE : ngildenhuys : not currently concerned with net types
package_identifier_matches_filename = true
package_item_not_in_package = true
parameter_default_value = false # NOTE : ngildenhuys : sometimes you want to enforce settng a parameter
parameter_explicit_type = true
parameter_in_generate = true
parameter_in_package = true
parameter_type_twostate = true # NOTE : ngildenhuys : could have problems with dtype parameters
# NOTE : ngildenhuys : all of these prefix onees have parameters but we are going with regexes for all naming enforcment
prefix_inout = false
prefix_input = false
prefix_instance = false
prefix_interface = false
prefix_module = false
prefix_output = false
prefix_package = false
# NOTE : end
procedural_continuous_assignment = true
program_identifier_matches_filename = true
# TODO : ngildenhuys : go over all regexes when going over options
re_forbidden_assert = false
re_forbidden_assert_property = false
re_forbidden_checker = false
re_forbidden_class = false
re_forbidden_function = false
re_forbidden_generateblock = false
re_forbidden_genvar = false
re_forbidden_instance = false
re_forbidden_interface = false
re_forbidden_localparam = false
re_forbidden_modport = false
re_forbidden_module_ansi = false
re_forbidden_module_nonansi = false
re_forbidden_package = false
re_forbidden_parameter = false
re_forbidden_port_inout = false
re_forbidden_port_input = false
re_forbidden_port_interface = false
re_forbidden_port_output = false
re_forbidden_port_ref = false
re_forbidden_program = false
re_forbidden_property = false
re_forbidden_sequence = false
re_forbidden_task = false
re_forbidden_var_class = false
re_forbidden_var_classmethod = false
re_required_assert = false
re_required_assert_property = false
re_required_checker = false
re_required_class = false
re_required_function = false
re_required_generateblock = false
re_required_genvar = false
re_required_instance = false
re_required_interface = false
re_required_localparam = false
re_required_modport = false
re_required_module_ansi = false
re_required_module_nonansi = false
re_required_package = false
re_required_parameter = false
re_required_port_inout = false
re_required_port_input = false
re_required_port_interface = false
re_required_port_output = false
re_required_port_ref = false
re_required_program = false
re_required_property = false
re_required_sequence = false
re_required_task = false
re_required_var_class = false
re_required_var_classmethod = false
# NOTE : end
# TODO : ngildenhuys : these forbid begin and end could be good rules but will
# have to lift up dv code
sequential_block_in_always_comb = false
sequential_block_in_always_ff = false
sequential_block_in_always_latch = false
style_commaleading = false
style_indent = true
style_keyword_0or1space = false
style_keyword_0space = false
style_keyword_1or2space = false
style_keyword_1space = false
style_keyword_construct = false
style_keyword_datatype = false
style_keyword_end = false
style_keyword_maybelabel = false
style_keyword_new = false
style_keyword_newline = false
style_operator_arithmetic = false
style_operator_arithmetic_leading_space = false
style_operator_boolean = false
style_operator_boolean_leading_space = false
style_operator_integer = false
style_operator_integer_leading_space = false
style_operator_unary = true
style_trailingwhitespace = true
tab_character = true # NOTE : ngildenhuys : is covered in another lint check but
unpacked_array = true # NOTE : ngildenhuys : may take some uplift in dv code
uppercamelcase_interface = false
uppercamelcase_module = false
uppercamelcase_package = false
